### ISSUE TITLE
Left and right menus not working on firefox

### ISSUE THREAD

**Issue by Silerty** [SubZane/flyPanels#1]
Hi,

First of all, thanks you for this great menu which is really fluid and answer my needs perfectly.

I have a problem on firefox, the right and the left menu are not working. When I click on the menu left button for example, the entire website become lighter, but the left menu don't appear.

**Comment by SubZane** [comment]
Hi

Could you please specify what OS and version of Firefox you are using? :)

**Comment by Silerty** [comment]
Hi, I'm on Mac OS X with Firefox 36.0

**Comment by SubZane** [comment]
I found the bug and fixed it :) Please check the latest version and demo online :)

**Comment by Silerty** [comment]
Cool, thanks for the rapidity !
