### ISSUE TITLE
Unavailable previous version

### ISSUE THREAD

**Issue by parken26** [SubZane/flyPanels#13]
Hi,
There is a link to the previous version in the description, however, it links back to the latest version.
I would appreciate if you could make this version available for download 
https://www.jqueryscript.net/demo/Sleek-Off-canvas-Push-Menu-Plugin-For-jQuery-FlyPanels/#
I prefer this for my project - thanks a lot.

**Comment by SubZane** [comment]
Sorry. I've killed the jQuery version as I haven't updated it for almost a decade. I have moved over to plain javascript and reactjs
