### ISSUE TITLE
Right menu content is always hidden

### ISSUE THREAD

**Issue by Silerty** [SubZane/flyPanels#2]
Hi,

There is a problem with the content of the right menu which is always hidden when we open it.
I have solved this by using the 'onOpenRight' event, but it is still an issue.

Thanks !

**Comment by SubZane** [comment]
Is this related to firefox as well?

**Comment by Silerty** [comment]
I have this problem on Chrome (with Mac OS). It's not related to the other issue I think.
I'm having this problem on your demo website for example. I only see the search bar on the right menu, the other items in the div ".panelcontent" are always hidden.

**Comment by SubZane** [comment]
I understand. Well, in the demo the search bar is only supposed to open. You set what panel to open using the data attributes

data-panel="search" targets data-panel="search"

so change data-panel to "iconmenu" to open that panel instead

**Comment by Silerty** [comment]
Okay it works great, thanks !
