### ISSUE TITLE
Issue with safari tab browsing ON nav dosent work when in landscape

### ISSUE THREAD

**Issue by chandra76** [SubZane/flyPanels#5]
Hi Subzane,

The feature on iphone safari with tab browsing ON  the navigation or tree menu seems not working when press on the nav bar (---) can you look at this issue and suggest a fix!!

**Comment by SubZane** [comment]
Hi and sorry for the late reply. Could you provide with a URL so I can see the error by myself?

**Comment by SubZane** [comment]
closing this since no reply
