### ISSUE TITLE
2.0 doesent work in many devices including iphone and ipad

### ISSUE THREAD

**Issue by palashjhabak** [SubZane/flyPanels#7]

**Comment by SubZane** [comment]
Please specify.

**Comment by palashjhabak** [comment]
Yeah sure. so the navigation drawer (navigation panel) doesent seme to open upon clicking the hamburger icon in the latest flypanel version. Even your demo http://www.andreasnorman.com/flypanels/# didnt work for me in iPad and iPhone (both safari and chrome)

**Comment by SubZane** [comment]
I mean browser versions and ios version as they work for me perfectly in chrome and safari on ios9

**Comment by palashjhabak** [comment]
iOS version: 8.0.2, chrome version: 46.0+

**Comment by SubZane** [comment]
I found what caused it and have updated flypanels to 2.0.1 that should fix. Thanks for reporting it :)
